In [8]:
import torch
print(torch.cuda.is_available())

True


In [13]:

tensor1 = torch.tensor([[1, 2], 
                          [3, 4]])
tensor2 = torch.tensor([[7, 8], 
                          [9, 10]])
print(tensor1.shape)

floattensor1 = tensor1.to(torch.float64)
print(floattensor1.type)
print(floattensor1.dtype)

multiTensor = tensor1.T.matmul(tensor2)
print(multiTensor)

torch.Size([2, 2])
<built-in method type of Tensor object at 0x00000164DBC18F00>
torch.float64
tensor([[34, 38],
        [50, 56]])


In [16]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad = True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)


(tensor([-0.0898]),)
(tensor([-0.0817]),)


NameError: name 'tokenizer' is not defined